### ISSUE TITLE
Error in Logs on first run

### ISSUE THREAD

**Issue by ChvckN0rri5** [bipinkrish/file-converter-telegram-bot#13]
Attaching to file-converter-bot_myservice_1
myservice_1  | local variable 'inputt' referenced before assignment
myservice_1  | Traceback (most recent call last):
myservice_1  |   File "/usr/local/lib/python3.10/dist-packages/pyrogram/dispatcher.py", line 242, in handler_worker
myservice_1  |     await self.loop.run_in_executor(
myservice_1  |   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
myservice_1  |     result = self.fn(*self.args, **self.kwargs)
myservice_1  |   File "/usr/src/app/main.py", line 1414, in text
myservice_1  |     oldext = inputt.split(".")[-1]
myservice_1  | UnboundLocalError: local variable 'inputt' referenced before assignment

**Comment by ChvckN0rri5** [comment]
Results in Channel
![IMG_7879](https://user-images.githubusercontent.com/99159971/236522757-8cdcc195-f5fa-45af-82fc-61c6b186142d.jpeg)

![IMG_7880](https://user-images.githubusercontent.com/99159971/236522932-463dbed3-e7c5-4a68-a342-a5da0aacd55f.jpeg)

**Comment by ChvckN0rri5** [comment]
All fixed. A rogue container was running on the old server... 

Carry on
