### ISSUE TITLE
No longer working not even /start command

### ISSUE THREAD

**Issue by mg8x** [bipinkrish/file-converter-telegram-bot#17]
The bot stopped working a month ago before that it was working well. even your official bot ([@FilesConvertRobot](https://t.me/filesconvertrobot))stopped working.

when I run it on Linux server: 
`docker run file-converter`

it shows this error:
```
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 1438, in <module>
    app.run()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/run.py", line 84, in run
    self.start()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/start.py", line 58, in start
    is_authorized = await self.connect()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/auth/connect.py", line 47, in connect
    await self.session.start()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 142, in start
    raise e
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 109, in start
    await self.send(raw.functions.Ping(ping_id=0), timeout=self.START_TIMEOUT)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 333, in send
    raise BadMsgNotification(result.error_code)
pyrogram.errors.BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized.
```
And thanks for hard work!!

**Comment by bipinkrish** [comment]
Please google the error

**Comment by mg8x** [comment]
fixed by changing version of pyrogram to its last version in requirements.txt then rebuild the docker image simply by
`docker build . -t file-converter`
then run it
`docker run file-converter`

**Comment by Ashrafmdmatin41** [comment]
> fixed by changing version of pyrogram to its last version in requirements.txt then rebuild the docker image simply by `docker build . -t file-converter` then run it `docker run file-converter`

Push it
